name: docs
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2  
      - name: vuepress-deploy 
        uses: jenkey2011/vuepress-deploy@master
        env:
         ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         TARGET_REPO: mcolomerc/cctools
         TARGET_BRANCH: gh-pages
         BUILD_SCRIPT: cd docs && npm install && npm run build && cd ..
         BUILD_DIR: docs/src/.vuepress/dist