name: release
on:
  push:
    branches:
      - main

  pull_request:
   types: [closed]
   
jobs: 
  goreleaser: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.20.3'
          cache: true 
      - name: setup release environment
        run: |-
          echo 'GITHUB_TOKEN=${{secrets.GORELEASER_ACCESS_TOKEN}}' > .release-env
      - name: release 
        run: make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      