name: release
on:
  pull_request: 
   types: [closed]  
jobs: 
  tag:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@master
      with:     
        fetch-depth: 0
    - name: Bump version and push tag
      uses: RueLaLa/auto-tagger@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_PR_NUMBER: ${{ github.event.number }}
  goreleaser: 
    needs: [tag]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: git fetch --force --tags
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.20.3'
          cache: true 
      - name: gcc-aarch64-linux
        run: |
          sudo apt-get -y install gcc-aarch64-linux-gnu g++-aarch64-linux-gnu 
      - name: setup release environment
        run: |-
          echo 'GITHUB_TOKEN=${{secrets.GITHUB_TOKEN}}' > .release-env
      - name: release publish
        run: make release
  docs:
    needs : [goreleaser]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
         ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         TARGET_REPO: marcelogft/gitops
         TARGET_BRANCH: gh-pages
         BUILD_SCRIPT: yarn && yarn build
         BUILD_DIR: docs/.vuepress/dist
      
