name: release
on:
  push:
    branches:
      - main

  pull_request:
   types: [closed]
   
jobs: 
  goreleaser: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.20.3'
          cache: true 
      - name: GCC multilib
        run: |
          sudo apt-get install gcc-multilib g++-multilib
      - uses: goreleaser/goreleaser-action@v5
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro':
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      